### ISSUE TITLE
<<< fullota failed

### ISSUE THREAD

**Issue by deamonpain** [FlymeOS/manifest#14]
I: Using Apktool 2.2.2-6a4ae2-SNAPSHOT on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
>>>> modify resource id: out/obj/system/framework/framework.board.Ybs/smali ...
<<<< modify resource id: out/obj/system/framework/framework.board.Ybs/smali done
>>>> modify resource id: out/obj/system/framework/framework.board.Ybs/smali_classes2 ...
<<<< modify resource id: out/obj/system/framework/framework.board.Ybs/smali_classes2 done
<<<< copy board packages done
>>>> in partSmaliAppend.sh
I: Using Apktool 2.2.2-6a4ae2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
out/obj/system/framework/framework.eP3/smali/android/content/res/Configuration.smali[3073,0] Cannot get the location of a label that hasn't been placed yet.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: android/content/res/Configuration.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:75)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:59)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:404)
	at brut.androlib.Androlib.buildSources(Androlib.java:335)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
/mnt/WorkSpace/flyme/build/main.mk:451: recipe for target 'out/obj/system/framework/framework.jar' failed
make[1]: *** [out/obj/system/framework/framework.jar] Error 161
make[1]: Leaving directory '/mnt/WorkSpace/flyme/devices/cm'
/mnt/WorkSpace/flyme/build/main.mk:34: recipe for target 'ota' failed
make: *** [ota] Error 2

[Configuration.smali.zip](https://github.com/FlymeOS/manifest/files/1127830/Configuration.smali.zip)
please help & thanks in advance

**Comment by hexiaoshuai** [comment]
This method :  `.method public diff(Landroid/content/res/Configuration;)I`
you patch error, `goto :goto_1` can not find `:goto_1`, maybe you delete some code
