### ISSUE TITLE
Settings FC

### ISSUE THREAD

**Issue by rorre** [FlymeOS/manifest#15]
Source: https://github.com/Rendyindo/Flyme_X510-cm
Log: https://puu.sh/wD2Dh/a47e364b18.log
Part of log:

```
07-06 21:01:56.837  4990  5563 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
07-06 21:01:56.837  4990  5563 E AndroidRuntime: Process: com.android.settings, PID: 4990
07-06 21:01:56.837  4990  5563 E AndroidRuntime: Theme: themes:{}
07-06 21:01:56.837  4990  5563 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.telephony.ITelephonyExt.getDeviceId(int)' on a null object reference
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at android.telephony.MzTelephonyManager.getDeviceId(MzTelephonyManager.java:557)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at android.telephony.MzTelephonyManager.getDeviceId(MzTelephonyManager.java:537)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.meizu.settings.utils.MzUtils.getDefaultIMEI(MzUtils.java:787)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.meizu.settings.recommended.RemoteConfigFetcher.<init>(RemoteConfigFetcher.java:62)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.meizu.settings.recommended.RecommendController.<init>(RecommendController.java:61)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.meizu.settings.recommended.RecommendController.getInstance(RecommendController.java:88)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.android.settings.SettingsActivity.updateTilesList(SettingsActivity.java:1301)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.android.settings.SettingsActivity.buildDashboardCategories(SettingsActivity.java:1061)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.android.settings.SettingsActivity.getDashboardCategories(SettingsActivity.java:430)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.meizu.settings.home.FlymeDashboardSummary$LoadingTask.doInBackground(FlymeDashboardSummary.java:434)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at com.meizu.settings.home.FlymeDashboardSummary$LoadingTask.doInBackground(FlymeDashboardSummary.java:428)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-06 21:01:56.837  4990  5563 E AndroidRuntime: 	... 3 more
```
---
```
07-06 20:56:50.604   792   792 W ActivityManager: Unable to start service Intent { cmp=com.android.phone/com.meizu.phone.MzTelephonyService } U=0: not found
```
---
```
07-06 20:58:04.538  4578  4578 W System.err: java.lang.ClassNotFoundException: com.android.internal.telephony.MzIccConstants
07-06 20:58:04.539  4578  4578 W System.err: 	at java.lang.Class.classForName(Native Method)
07-06 20:58:04.539  4578  4578 W System.err: 	at java.lang.Class.forName(Class.java:324)
07-06 20:58:04.539  4578  4578 W System.err: 	at java.lang.Class.forName(Class.java:285)
07-06 20:58:04.539  4578  4578 W System.err: 	at com.a.a.a.c.f.a(SourceFile:35)
07-06 20:58:04.539  4578  4578 W System.err: 	at com.meizu.d.e.<clinit>(SourceFile:21)
07-06 20:58:04.539  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.n.<clinit>(SourceFile:284)
07-06 20:58:04.539  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.n.a(SourceFile:276)
07-06 20:58:04.539  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.SimEventReceiver.a(SourceFile:170)
07-06 20:58:04.540  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.SimEventReceiver.onReceive(SourceFile:211)
07-06 20:58:04.540  4578  4578 W System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2757)
07-06 20:58:04.540  4578  4578 W System.err: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-06 20:58:04.540  4578  4578 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
07-06 20:58:04.540  4578  4578 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 20:58:04.540  4578  4578 W System.err: 	at android.os.Looper.loop(Looper.java:148)
07-06 20:58:04.540  4578  4578 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
07-06 20:58:04.540  4578  4578 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 20:58:04.540  4578  4578 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-06 20:58:04.540  4578  4578 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-06 20:58:04.541  4578  4578 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.telephony.MzIccConstants" on path: DexPathList[[zip file "/system/app/MzSimContacts/MzSimContacts.apk"],nativeLibraryDirectories=[/system/app/MzSimContacts/lib/arm, /vendor/lib, /system/lib]]
07-06 20:58:04.541  4578  4578 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-06 20:58:04.541  4578  4578 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-06 20:58:04.541  4578  4578 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-06 20:58:04.541  4578  4578 W System.err: 	... 18 more
07-06 20:58:04.541  4578  4578 W System.err: 	Suppressed: java.lang.ClassNotFoundException: com.android.internal.telephony.MzIccConstants
07-06 20:58:04.542  4578  4578 W System.err: 		at java.lang.Class.classForName(Native Method)
07-06 20:58:04.542  4578  4578 W System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-06 20:58:04.542  4578  4578 W System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-06 20:58:04.542  4578  4578 W System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-06 20:58:04.542  4578  4578 W System.err: 		... 19 more
07-06 20:58:04.542  4578  4578 W System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
07-06 20:58:04.543  4578  4578 W System.err: java.lang.ClassNotFoundException: com.android.internal.telephony.MzIccConstants
07-06 20:58:04.543  4578  4578 W System.err: 	at java.lang.Class.classForName(Native Method)
07-06 20:58:04.543  4578  4578 W System.err: 	at java.lang.Class.forName(Class.java:324)
07-06 20:58:04.543  4578  4578 W System.err: 	at java.lang.Class.forName(Class.java:285)
07-06 20:58:04.543  4578  4578 W System.err: 	at com.a.a.a.c.f.a(SourceFile:35)
07-06 20:58:04.543  4578  4578 W System.err: 	at com.meizu.d.e.<clinit>(SourceFile:34)
07-06 20:58:04.544  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.n.<clinit>(SourceFile:284)
07-06 20:58:04.544  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.n.a(SourceFile:276)
07-06 20:58:04.544  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.SimEventReceiver.a(SourceFile:170)
07-06 20:58:04.544  4578  4578 W System.err: 	at com.meizu.mzsimcontacts.SimEventReceiver.onReceive(SourceFile:211)
07-06 20:58:04.544  4578  4578 W System.err: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2757)
07-06 20:58:04.544  4578  4578 W System.err: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-06 20:58:04.544  4578  4578 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
07-06 20:58:04.544  4578  4578 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 20:58:04.544  4578  4578 W System.err: 	at android.os.Looper.loop(Looper.java:148)
07-06 20:58:04.544  4578  4578 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
07-06 20:58:04.544  4578  4578 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 20:58:04.545  4578  4578 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-06 20:58:04.545  4578  4578 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-06 20:58:04.545  4578  4578 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.internal.telephony.MzIccConstants" on path: DexPathList[[zip file "/system/app/MzSimContacts/MzSimContacts.apk"],nativeLibraryDirectories=[/system/app/MzSimContacts/lib/arm, /vendor/lib, /system/lib]]
07-06 20:58:04.545  4578  4578 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-06 20:58:04.545  4578  4578 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-06 20:58:04.545  4578  4578 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-06 20:58:04.546  4578  4578 W System.err: 	... 18 more
07-06 20:58:04.546  4578  4578 W System.err: 	Suppressed: java.lang.ClassNotFoundException: com.android.internal.telephony.MzIccConstants
07-06 20:58:04.546  4578  4578 W System.err: 		at java.lang.Class.classForName(Native Method)
07-06 20:58:04.546  4578  4578 W System.err: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-06 20:58:04.546  4578  4578 W System.err: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-06 20:58:04.546  4578  4578 W System.err: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-06 20:58:04.546  4578  4578 W System.err: 		... 19 more
07-06 20:58:04.547  4578  4578 W System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

Extra infos: It wasn't FC at 6.7.6.5

Any help? Thanks in advance

**Comment by rorre** [comment]
Fixed.
