### ISSUE TITLE
fullota failure

### ISSUE THREAD

**Issue by Qiangong2** [FlymeOS/manifest#25]
`>>>> modify resource id: out/obj/system/framework/framework.board.DWd/smali ...
<<<< modify resource id: out/obj/system/framework/framework.board.DWd/smali done
>>>> modify resource id: out/obj/system/framework/framework.board.DWd/smali_classes2 ...
<<<< modify resource id: out/obj/system/framework/framework.board.DWd/smali_classes2 done
<<<< copy board packages done
>>>> in partSmaliAppend.sh
I: Using Apktool 2.2.2-6a4ae2-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65889
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:329)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1027)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:803)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:252)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:230)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:404)
	at brut.androlib.Androlib.buildSources(Androlib.java:335)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)

make[1]: *** [out/obj/system/framework/framework.jar] Error 161`

**Comment by imhansai** [comment]
@Qiangong2 把base的custom_jar.sh拷过来再fullota试试

**Comment by Qiangong2** [comment]
@hanandjun 不工作。 和之前一样

**Comment by michal161** [comment]
Did You fixed?
