### ISSUE TITLE
Flyme Newproject中断

### ISSUE THREAD

**Issue by CCC-Batch** [FlymeOS/manifest#3]
>>> normalize the out/oem_target_files.zip ...
D/reverse: Program args = []
I/reverse-zipformatter: unzip /home/ccc/flymeos/devices/z2131_mk/out/oem_target_files.zip to /tmp/tmpCIjiMN
D/reverse-zipformatter: 
Traceback (most recent call last):
  File "/home/ccc/flymeos/tools/otanormalize", line 38, in <module>
    ZipFormatter.create(OPTIONS).format()
  File "/home/ccc/flymeos/tools/reverses/zipformatter.py", line 84, in create
    zipType = zipModel.getZipType()
  File "/home/ccc/flymeos/tools/reverses/zipformatter.py", line 235, in getZipType
    if libType.find("art") >= 0:
UnboundLocalError: local variable 'libType' referenced before assignment
/home/ccc/flymeos/build/newproject.mk:30: recipe for target 'out/oem_target_files.zip.std.zip' failed
make: *** [out/oem_target_files.zip.std.zip] Error 1

**Comment by gesangtome** [comment]
deodex失败，请自行合并framework 和applications，问题解决

**Comment by wyunlingy** [comment]
请问楼上怎么合并？

**Comment by VadeBin** [comment]
why not for android 5.1 lollipop,very bad(
