### ISSUE TITLE
bootloooooop

### ISSUE THREAD

**Issue by sky0hjh** [FlymeOS/manifest#31]
用AOSP 7.1适配了个Flyme刷入之后无限卡在开机动画处，log如下
12-10 03:13:46.371   891   891 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
12-10 03:13:46.371   891   891 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.USER_STARTED flg=0x50000010 (has extras) } in com.android.server.ConnectivityService$3@9394c57
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:355)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:222)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-10 03:13:46.371   891   891 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.exist(java.lang.String, int)' on a null object reference
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at android.security.KeyStore.contains(KeyStore.java:200)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at android.security.KeyStore.contains(KeyStore.java:208)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.server.net.LockdownVpnTracker.isEnabled(LockdownVpnTracker.java:90)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.server.ConnectivityService.onUserStart(ConnectivityService.java:3930)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.server.ConnectivityService.-wrap27(ConnectivityService.java)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at com.android.server.ConnectivityService$3.onReceive(ConnectivityService.java:3984)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
12-10 03:13:46.371   891   891 E AndroidRuntime: 	... 8 more

请问该如何解决？

**Comment by ChenZesen** [comment]
情况一样，对呀怎么解决呢
