### ISSUE TITLE
Make framework.jar失败

### ISSUE THREAD

**Issue by Huleee** [FlymeOS/manifest#40]
您好，开发者叔叔们，我遇到了像下面的问题不知如何解决

> Check project G720T ...
< Check project G720T done
> build |target-files|PREBUILT,OTA,META,SYSTEM| ...
>> generate |target-files|PREBUILT| ...
make[1]: Entering directory '/home/huleee/Flyme/devices/G720T'
<< generate |target-files|PREBUILT| done
>> generate |target-files|OTA| ...
<< generate |target-files|OTA| done
>> generate |target-files|BOOT| ...
<< generate |target-files|BOOT| done
>> prepare boot ramdisk from /home/huleee/Flyme/devices/G720T/boot.img.out ...
<< prepare boot ramdisk from /home/huleee/Flyme/devices/G720T/boot.img.out done
>> pack out/obj/BOOT to out/boot.img ...
Pack QCOM out/obj/BOOT --> out/merged_target_files/BOOTABLE_IMAGES/boot.img
<< pack out/obj/BOOT to out/boot.img done
* build boot.img out ==> out/boot.img
 
* use prebuilt recovery.img
 
>>> generating mac_permissions ...
<<< generating mac_permissions.mxl done
* mac_permissions.xml out ==> out/merged_target_files/SYSTEM/etc/security/mac_permissions.xml
 
* build framework-res out ==> out/merged_target_files/SYSTEM/framework/framework-res.apk
 
>>> build |target-files|SYSTEM|vendor_modify_jar| to out/obj/system/framework/framework.jar ...
>>>> copy board packages: "flyme meizu com/flyme com/meizu"
 		from /home/huleee/Flyme/devices/G720T/board/system/framework/framework.jar to 
I: Using Apktool 2.1.1-04d478-SNAPSHOT on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
>>>> modify resource id: out/obj/system/framework/framework.board.YCF/smali ...
<<<< modify resource id: out/obj/system/framework/framework.board.YCF/smali done
>>>> modify resource id: out/obj/system/framework/framework.board.YCF/smali_classes2 ...
<<<< modify resource id: out/obj/system/framework/framework.board.YCF/smali_classes2 done
<<<< copy board packages done
>>>> in partSmaliAppend.sh
>>> in custom_jar framework
'out/obj/system/framework/framework.Fdq/smali/android/accounts' -> 'out/obj/system/framework/framework.Fdq/smali_classes2/android/accounts'
'out/obj/system/framework/framework.Fdq/smali/android/hardware' -> 'out/obj/system/framework/framework.Fdq/smali_classes2/android/hardware'
'out/obj/system/framework/framework.Fdq/smali/android/printservice' -> 'out/obj/system/framework/framework.Fdq/smali_classes2/android/printservice'
'out/obj/system/framework/framework.Fdq/smali/android/speech' -> 'out/obj/system/framework/framework.Fdq/smali_classes2/android/speech'
I: Using Apktool 2.1.1-04d478-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.IllegalStateException: Cannot get the location of a label that hasn't been placed yet.
	at org.jf.dexlib2.builder.Label.getLocation(Label.java:54)
	at org.jf.dexlib2.builder.Label.getCodeAddress(Label.java:48)
	at org.jf.dexlib2.builder.BuilderOffsetInstruction.internalGetCodeOffset(BuilderOffsetInstruction.java:60)
	at org.jf.dexlib2.builder.BuilderOffsetInstruction.getCodeOffset(BuilderOffsetInstruction.java:50)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:206)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:988)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:803)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:252)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:230)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:53)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:364)
	at brut.androlib.Androlib.buildSources(Androlib.java:295)
	at brut.androlib.Androlib.build(Androlib.java:278)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
/home/huleee/Flyme/build/main.mk:451: recipe for target 'out/obj/system/framework/framework.jar' failed
make[1]: *** [out/obj/system/framework/framework.jar] Error 161
make[1]: Leaving directory '/home/huleee/Flyme/devices/G720T'
/home/huleee/Flyme/build/main.mk:34: recipe for target 'ota' failed
make: *** [ota] Error 2

**Comment by xiaxiaxiaxia** [comment]
同样的问题。。。。

**Comment by ZJKZJ** [comment]
牛批

**Comment by 380121850** [comment]
叔叔们。。。

**Comment by 380121850** [comment]
ERR_USB_NOT_CONNECTED: Can not find device
Please make sure your device has been connected.

<<< config failed
我很奇怪，为什么要连接手机才行！！
